# Habilitar soporte AndroidX
android.useAndroidX=true

# Optimizar generacion de recursos R
android.nonTransitiveRClass=true

# Opciones de memoria para Gradle Daemon y Kotlin Daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Optimizaciones de compilacion y ejecucion de Kotlin
org.gradle.parallel=true
org.gradle.caching=true
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
