# Habilitar soporte AndroidX
android.useAndroidX=true

# Optimizar generacion de recursos R
android.nonTransitiveRClass=true

# Opciones de memoria para Gradle Daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Optimizaciones de compilacion
org.gradle.parallel=true
org.gradle.caching=true
